// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: drowsiness.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_drowsiness_proto protoreflect.FileDescriptor

var file_drowsiness_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x72, 0x6f, 0x77, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x32, 0x13, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x77, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_drowsiness_proto_goTypes = []interface{}{}
var file_drowsiness_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drowsiness_proto_init() }
func file_drowsiness_proto_init() {
	if File_drowsiness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drowsiness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drowsiness_proto_goTypes,
		DependencyIndexes: file_drowsiness_proto_depIdxs,
	}.Build()
	File_drowsiness_proto = out.File
	file_drowsiness_proto_rawDesc = nil
	file_drowsiness_proto_goTypes = nil
	file_drowsiness_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DrowsinessServiceClient is the client API for DrowsinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrowsinessServiceClient interface {
}

type drowsinessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDrowsinessServiceClient(cc grpc.ClientConnInterface) DrowsinessServiceClient {
	return &drowsinessServiceClient{cc}
}

// DrowsinessServiceServer is the server API for DrowsinessService service.
type DrowsinessServiceServer interface {
}

// UnimplementedDrowsinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDrowsinessServiceServer struct {
}

func RegisterDrowsinessServiceServer(s *grpc.Server, srv DrowsinessServiceServer) {
	s.RegisterService(&_DrowsinessService_serviceDesc, srv)
}

var _DrowsinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DrowsinessService",
	HandlerType: (*DrowsinessServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "drowsiness.proto",
}
